#Start with a base image containing Java runtime
FROM openjdk:17.0.1-slim
# Add Maintainer Info
LABEL maintainer="bykwarb <nebykwarb@gmail.com>"
# The application's jar file
ARG JAR_FILE=target/*.jar
# Add the application's jar to the container
COPY ${JAR_FILE} app.jar
#execute the application
ENTRYPOINT ["java","-jar","/app.jar"]